// oxlint-disable effect/noGlobals -- Bun.Glob, Bun.file, and Bun.write read the built package and write the consumer module: the rule checks what a consumer installs.
import { Effect, Schema } from "effect";

/**
 * The published subpaths, as a build rule.
 *
 * A package's `exports` map is a promise: each subpath names the
 * declaration file a consumer's compiler reads and the module its runtime
 * loads. The build can stop writing one, or an entry can name a path the
 * build never wrote, and every test still passes, because the tests read
 * the source. So the rule reads the map after the build: each `types` and
 * `default` file must exist, and the consumer project imports every
 * subpath by its public name, so one that does not resolve fails `tsc`.
 */

/** One `exports` entry as the build publishes it. */
const Entry = Schema.Struct({
  types: Schema.String,
  default: Schema.String,
});

const Manifest = Schema.fromJsonString(
  Schema.Struct({
    name: Schema.String,
    exports: Schema.Record(Schema.String, Entry),
  }),
);

/** Only whether a manifest is private, so a private package's other fields go unread. */
const Visibility = Schema.fromJsonString(
  Schema.Struct({ private: Schema.optionalKey(Schema.Boolean) }),
);

/** One published subpath: its key in `exports`, and the two files it names. */
export interface Subpath {
  readonly key: string;
  readonly types: string;
  readonly default: string;
}

/** A package's name and every subpath its `exports` map publishes, in map order. */
export const decodeSubpaths = (manifest: string) =>
  Effect.map(Schema.decodeEffect(Manifest)(manifest), (decoded) => ({
    name: decoded.name,
    subpaths: Object.entries(decoded.exports).map(([key, entry]): Subpath => ({
      key,
      types: entry.types,
      default: entry.default,
    })),
  }));

/** A file the exports map promises and the build did not write. */
export interface MissingFile {
  readonly key: string;
  readonly field: "types" | "default";
  readonly file: string;
}

const fields: ReadonlyArray<MissingFile["field"]> = ["types", "default"];

/** Every promised file that `exists` does not find, subpath by subpath. */
export const missingFiles = (
  subpaths: ReadonlyArray<Subpath>,
  exists: (file: string) => boolean,
): ReadonlyArray<MissingFile> =>
  subpaths.flatMap((subpath) =>
    fields.flatMap((field): ReadonlyArray<MissingFile> => {
      if (exists(subpath[field])) {
        return [];
      }
      return [{ key: subpath.key, field, file: subpath[field] }];
    }),
  );

/** The specifier a consumer writes for a subpath: `./view` of `effect-frame` is `effect-frame/view`. */
const specifierOf = (name: string, key: string): string => `${name}${key.replace(/^\./, "")}`;

/**
 * A consumer module that re-exports every subpath as a namespace. It is
 * generated, so a subpath added to the map is checked with no edit here.
 */
export const consumerModule = (name: string, subpaths: ReadonlyArray<Subpath>): string =>
  [
    `// Generated by \`bun run declarations\` from ${name}'s exports map. Do not edit.`,
    ...subpaths.map(
      (subpath, index) => `export * as S${String(index)} from "${specifierOf(name, subpath.key)}";`,
    ),
    "",
  ].join("\n");

/** One published package's subpaths, checked, with the files it is missing. */
export interface CheckedPackage {
  readonly name: string;
  readonly subpaths: number;
  readonly missing: ReadonlyArray<MissingFile>;
}

const checkPackage = Effect.fn("Subpaths.checkPackage")(function* (
  root: string,
  directory: string,
  manifest: string,
) {
  const { name, subpaths } = yield* decodeSubpaths(manifest);
  const promised = subpaths.flatMap((subpath) => [subpath.types, subpath.default]);
  const found = yield* Effect.forEach(
    promised,
    (file) =>
      Effect.map(
        Effect.promise(() => Bun.file(`${root}/${directory}/${file}`).exists()),
        (exists) => ({ file, exists }),
      ),
    { concurrency: 8 },
  );
  const built = new Set(found.filter((one) => one.exists).map((one) => one.file));
  const consumer = `${root}/tooling/checks/consumer/generated/${directory.replace(/^packages\//, "")}.ts`;
  yield* Effect.promise(() => Bun.write(consumer, consumerModule(name, subpaths)));
  return {
    name,
    subpaths: subpaths.length,
    missing: missingFiles(subpaths, (file) => built.has(file)),
  } satisfies CheckedPackage;
});

/**
 * Every package under `root/packages` that is not private: each promised
 * file checked, and its consumer module written for `tsc -p consumer`.
 */
export const checkSubpaths = Effect.fn("Subpaths.checkSubpaths")(function* (root: string) {
  const manifests = Array.from(
    new Bun.Glob("packages/*/package.json").scanSync({ cwd: root }),
  ).toSorted();
  const read = yield* Effect.forEach(manifests, (manifest) =>
    Effect.map(
      Effect.promise(() => Bun.file(`${root}/${manifest}`).text()),
      (text) => ({ directory: manifest.replace(/\/package\.json$/, ""), text }),
    ),
  );
  const visible = yield* Effect.forEach(read, (one) =>
    Effect.map(Schema.decodeEffect(Visibility)(one.text), (visibility) => ({
      ...one,
      published: visibility.private !== true,
    })),
  );
  return yield* Effect.forEach(
    visible.filter((one) => one.published),
    (one) => checkPackage(root, one.directory, one.text),
  );
});

/** One missing file as the gate prints it. */
export const formatMissing = (name: string, missing: MissingFile): string =>
  `${name} exports ${missing.key} ${missing.field}: ${missing.file} was not built`;
