import { Form, Generated } from "effect-frame/actor/client";
import type { MessageOf, RemoteActorRef } from "effect-frame/actor/client";
import { View } from "effect-frame/view";
import { Effect, Schema, SchemaTransformation } from "effect";
import { describe, expect, test } from "bun:test";
import { Event } from "effect-machine";
import type { AddTask } from "../plain-form-fixture.js";
import { Tasks, TasksMessage, board } from "../plain-form-fixture.js";

/**
 * Compile-time refusals for plain-form posts (#21 §1.5) and generated
 * fields (#32 §3, §8). Each `@ts-expect-error` is a claim: remove the rule
 * it stands on and `bun run typecheck` fails on the unused directive.
 */

type Equals<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false;

// --- One message schema, two codecs, one type (#21 §1.4) -------------------

const formCodec = Form.codec(TasksMessage);
const bothCodecsYieldOneType: Equals<
  Schema.Schema.Type<typeof formCodec>,
  Schema.Schema.Type<typeof Tasks.message>
> = true;

// --- A generated field is absent from the message an author constructs ----

type AddInput = Extract<Generated.Input<typeof TasksMessage>, { readonly _tag: "AddTask" }>;
const addInputOmitsId: Equals<keyof AddInput, "_tag" | "title" | "done" | "note"> = true;
const addTypeKeepsIdRequired: Equals<
  Pick<Schema.Schema.Type<typeof AddTask>, "id">,
  { readonly id: string }
> = true;

declare const tasks: RemoteActorRef<typeof Tasks>;
const sendWithoutId = () =>
  Generated.send(tasks, Tasks, { _tag: "AddTask", title: "milk", done: false });
const sendWithId = () =>
  // @ts-expect-error the author never writes a generated field
  Generated.send(tasks, Tasks, { _tag: "AddTask", id: "x", title: "milk", done: false });

// --- A generated field cannot carry a decoding default --------------------

const defaultOverGenerated = () =>
  Generated.fromCommandId(Schema.String).pipe(
    // @ts-expect-error no literal satisfies the minted brand
    Schema.withDecodingDefault(Effect.succeed("x")),
  );
const generatedOverDefault = () =>
  // @ts-expect-error a field with a decoding default is optional when encoded
  Generated.fromCommandId(Schema.String.pipe(Schema.withDecodingDefault(Effect.succeed("x"))));
// @ts-expect-error a generated field is a string
const generatedNumber = () => Generated.fromCommandId(Schema.Finite);

// --- What has no form encoding does not build (#21 §1.5) ------------------

const Upload = Schema.Union([
  Schema.TaggedStruct("Upload", { name: Schema.String, bytes: Schema.Uint8Array }),
]);
// @ts-expect-error a Uint8Array field has no form encoding
const uploadCodec = () => Form.codec(Upload);

// --- A machine's event schema is a form message too (#105) ---------------

const ApplyEvent = Event({
  SetAbout: { name: Schema.String, age: Schema.FiniteFromString, subscribe: Form.Checkbox },
  Submit: {},
});
const machineCodec = Form.codec(ApplyEvent);
const machineCodecYieldsTheEvent: Equals<
  Schema.Schema.Type<typeof machineCodec>,
  Schema.Schema.Type<typeof ApplyEvent>
> = true;
const UploadEvent = Event({
  Named: { name: Schema.String },
  Upload: { bytes: Schema.Uint8Array },
});
// @ts-expect-error a Uint8Array field in one machine event has no form encoding
const uploadEventCodec = () => Form.codec(UploadEvent);

// A schema that is not a machine's event schema gains nothing from a
// `variants` property: the refusal reads the schema itself.
const Posing = Object.assign(
  Schema.TaggedStruct("Upload", { name: Schema.String, bytes: Schema.Uint8Array }),
  { variants: { Upload: Schema.TaggedStruct("Upload", { name: Schema.String }) } },
);
// @ts-expect-error a `variants` property does not make a schema a machine's events
const posingCodec = () => Form.codec(Posing);

const BooleanFromOn = Schema.String.pipe(
  Schema.decodeTo(
    Schema.Boolean,
    SchemaTransformation.transform({ decode: (value) => value === "on", encode: () => "on" }),
  ),
);
const SetDone = Schema.TaggedStruct("SetDone", { id: Schema.String, done: BooleanFromOn });
// @ts-expect-error a form-bound boolean without a decoding default fails to build
const setDoneCodec = () => Form.codec(SetDone);
const checkboxCodec = () =>
  Form.codec(Schema.TaggedStruct("SetDone", { id: Schema.String, done: Form.Checkbox }));

// --- A form-bound message with an unmarked missing field does not compile --

const Rename = Schema.TaggedStruct("AddTask", {
  id: Schema.String,
  title: Schema.String,
  done: Form.Checkbox,
});
declare const renamed: RemoteActorRef<typeof Tasks>;

const coveredForm = () =>
  View.form({
    ref: renamed,
    contract: Tasks,
    key: board,
    message: Rename,
    typed: ["id", "title"],
    endpoint: "/actors",
    returnTo: "/",
  });
const uncoveredForm = () =>
  View.form({
    ref: renamed,
    contract: Tasks,
    key: board,
    // @ts-expect-error `id` is typed by no input and generated by no mark
    message: Rename,
    typed: ["title"],
    endpoint: "/actors",
    returnTo: "/",
  });

const generatedIsCovered = () =>
  View.form({
    ref: tasks,
    contract: Tasks,
    key: board,
    message: Tasks.raw.message.members[0],
    typed: ["title"],
    endpoint: "/actors",
    returnTo: "/",
  });

describe("plain-form types", () => {
  test("the refusals above are compile-time claims", () => {
    expect([
      bothCodecsYieldOneType,
      addInputOmitsId,
      addTypeKeepsIdRequired,
      machineCodecYieldsTheEvent,
    ]).toEqual([true, true, true, true]);
    const unused: ReadonlyArray<unknown> = [
      sendWithoutId,
      sendWithId,
      defaultOverGenerated,
      generatedOverDefault,
      generatedNumber,
      uploadCodec,
      setDoneCodec,
      checkboxCodec,
      coveredForm,
      uncoveredForm,
      generatedIsCovered,
      formCodec,
      uploadEventCodec,
      posingCodec,
    ];
    expect(unused).toHaveLength(14);
    const message: MessageOf<typeof Tasks> = { _tag: "AddTask", id: "c1", title: "t", done: true };
    expect(message._tag).toBe("AddTask");
  });
});
